[build]
  publish = "frontend"

[dev]
  command = "cd frontend && python -m http.server 8000"
  port = 8000

[[redirects]]
  from = "/api/*"
  to = "https://bluetechind.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
