services:
  - type: web
    name: bleu-tech-backend
    env: node
    plan: free
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: MONGO_URI
        scope: all
        value: mongodb+srv://raniel:raniel1432@raniel.skzmuxw.mongodb.net/MarineBlue
